/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query GetProductCategories {\n    productCategories(first: 10) {\n      nodes {\n        id\n        name\n        slug\n        description\n        image {\n          sourceUrl\n          altText\n        }\n        count\n      }\n    }\n  }\n": typeof types.GetProductCategoriesDocument,
    "\n  query GetDynamicProductsByCategory($categoriaSlug: [String], $cantidad: Int) {\n    productosPorCategoria: products(where: { categoryIn: $categoriaSlug }, first: $cantidad) {\n      nodes {\n        id\n        name\n        slug\n        ... on Product {\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n        ... on SimpleProduct {\n          price\n          regularPrice\n          salePrice\n          shortDescription\n          onSale\n          stockStatus\n          stockQuantity\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n        ... on VariableProduct {\n          price\n          regularPrice\n          salePrice\n          shortDescription\n          onSale\n          stockStatus\n          stockQuantity\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetDynamicProductsByCategoryDocument,
    "\n  query GetFullVariableProduct($slug: ID!) {\n    product(id: $slug, idType: SLUG) {\n      ... on VariableProduct {\n        id\n        name\n        slug\n        price\n        regularPrice\n        salePrice\n        onSale\n        stockStatus\n        stockQuantity\n        shortDescription\n        description\n        featuredImage {\n          node {\n            sourceUrl\n            altText\n          }\n        }\n        galleryImages {\n          nodes {\n            sourceUrl\n            altText\n          }\n        }\n        productCategories {\n          nodes {\n            id\n            name\n            slug\n          }\n        }\n        attributes {\n          nodes {\n            id\n            name\n            options\n          }\n        }\n        variations(first: 50) {\n          nodes {\n            id\n            name\n            sku\n            price\n            stockStatus\n            stockQuantity\n            attributes {\n              nodes {\n                name\n                value\n              }\n            }\n            image {\n              sourceUrl\n              altText\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetFullVariableProductDocument,
    "\n  query GetProductsByCategory($categorySlug: ID!, $first: Int = 12) {\n    productCategory(id: $categorySlug, idType: SLUG) {\n      id\n      name\n      slug\n      description\n      image {\n        sourceUrl\n        altText\n      }\n      products(first: $first) {\n        nodes {\n          id\n          name\n          slug\n          ... on ProductWithPricing {\n            price\n            regularPrice\n            salePrice\n          }\n          ... on SimpleProduct {\n            stockStatus\n            onSale\n          }\n          ... on VariableProduct {\n            stockStatus\n            onSale\n          }\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n          productCategories {\n            nodes {\n              id\n              name\n              slug\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetProductsByCategoryDocument,
    "\n  query GetVariableProductsByCategory($category: String!, $first: Int = 50) {\n    products(where: { category: $category }, first: $first) {\n      nodes {\n        ... on VariableProduct {\n          id\n          name\n          slug\n          price\n          productCategories {\n            nodes {\n              name\n              slug\n            }\n          }\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetVariableProductsByCategoryDocument,
    "\n  query SearchProducts($search: String!, $first: Int = 20) {\n    products(where: { search: $search }, first: $first) {\n      nodes {\n        id\n        name\n        slug\n        ... on VariableProduct {\n          price\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.SearchProductsDocument,
    "\n  query GetProductsByCategoryWithFragments($slug: String!, $first: Int = 100) {\n    products(where: { category: $slug }, first: $first) {\n      nodes {\n        id\n        slug\n        name\n        __typename\n        shortDescription\n        description\n        ... on ProductWithPricing {\n          price\n        }\n        ... on Product {\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n          productCategories {\n            nodes {\n              id\n              name\n              slug\n            }\n          }\n        }\n        ... on VariableProduct {\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n        ... on SimpleProduct {\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetProductsByCategoryWithFragmentsDocument,
    "\n  query GetPosts {\n    posts(first: 10, where: { orderby: { field: DATE, order: DESC } }) {\n      nodes {\n        id\n        title\n        excerpt\n        slug\n        date\n        featuredImage {\n          node {\n            sourceUrl\n            altText\n            mediaDetails {\n              width\n              height\n            }\n          }\n        }\n        author {\n          node {\n            name\n          }\n        }\n        categories {\n          nodes {\n            name\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetPostsDocument,
    "\n  query GetPostBySlug($slug: ID!) {\n    post(id: $slug, idType: SLUG) {\n      title\n      excerpt\n      content\n      date\n      featuredImage {\n        node {\n          sourceUrl\n          altText\n        }\n      }\n      author {\n        node {\n          name\n          avatar {\n            url\n          }\n        }\n      }\n      categories {\n        nodes {\n          name\n          slug\n        }\n      }\n    }\n  }\n": typeof types.GetPostBySlugDocument,
    "\n  query GetAllPostsSlugs {\n    posts(first: 100) {\n      nodes {\n        slug\n      }\n    }\n  }\n": typeof types.GetAllPostsSlugsDocument,
    "\n  query GetSEOPageContent($slug: String!) {\n    pages(where: { name: $slug }) {\n      nodes {\n        databaseId\n        title\n        content\n        slug\n        date\n        modified\n        featuredImage {\n          node {\n            sourceUrl\n            altText\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetSeoPageContentDocument,
};
const documents: Documents = {
    "\n  query GetProductCategories {\n    productCategories(first: 10) {\n      nodes {\n        id\n        name\n        slug\n        description\n        image {\n          sourceUrl\n          altText\n        }\n        count\n      }\n    }\n  }\n": types.GetProductCategoriesDocument,
    "\n  query GetDynamicProductsByCategory($categoriaSlug: [String], $cantidad: Int) {\n    productosPorCategoria: products(where: { categoryIn: $categoriaSlug }, first: $cantidad) {\n      nodes {\n        id\n        name\n        slug\n        ... on Product {\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n        ... on SimpleProduct {\n          price\n          regularPrice\n          salePrice\n          shortDescription\n          onSale\n          stockStatus\n          stockQuantity\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n        ... on VariableProduct {\n          price\n          regularPrice\n          salePrice\n          shortDescription\n          onSale\n          stockStatus\n          stockQuantity\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetDynamicProductsByCategoryDocument,
    "\n  query GetFullVariableProduct($slug: ID!) {\n    product(id: $slug, idType: SLUG) {\n      ... on VariableProduct {\n        id\n        name\n        slug\n        price\n        regularPrice\n        salePrice\n        onSale\n        stockStatus\n        stockQuantity\n        shortDescription\n        description\n        featuredImage {\n          node {\n            sourceUrl\n            altText\n          }\n        }\n        galleryImages {\n          nodes {\n            sourceUrl\n            altText\n          }\n        }\n        productCategories {\n          nodes {\n            id\n            name\n            slug\n          }\n        }\n        attributes {\n          nodes {\n            id\n            name\n            options\n          }\n        }\n        variations(first: 50) {\n          nodes {\n            id\n            name\n            sku\n            price\n            stockStatus\n            stockQuantity\n            attributes {\n              nodes {\n                name\n                value\n              }\n            }\n            image {\n              sourceUrl\n              altText\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetFullVariableProductDocument,
    "\n  query GetProductsByCategory($categorySlug: ID!, $first: Int = 12) {\n    productCategory(id: $categorySlug, idType: SLUG) {\n      id\n      name\n      slug\n      description\n      image {\n        sourceUrl\n        altText\n      }\n      products(first: $first) {\n        nodes {\n          id\n          name\n          slug\n          ... on ProductWithPricing {\n            price\n            regularPrice\n            salePrice\n          }\n          ... on SimpleProduct {\n            stockStatus\n            onSale\n          }\n          ... on VariableProduct {\n            stockStatus\n            onSale\n          }\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n          productCategories {\n            nodes {\n              id\n              name\n              slug\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetProductsByCategoryDocument,
    "\n  query GetVariableProductsByCategory($category: String!, $first: Int = 50) {\n    products(where: { category: $category }, first: $first) {\n      nodes {\n        ... on VariableProduct {\n          id\n          name\n          slug\n          price\n          productCategories {\n            nodes {\n              name\n              slug\n            }\n          }\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetVariableProductsByCategoryDocument,
    "\n  query SearchProducts($search: String!, $first: Int = 20) {\n    products(where: { search: $search }, first: $first) {\n      nodes {\n        id\n        name\n        slug\n        ... on VariableProduct {\n          price\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n      }\n    }\n  }\n": types.SearchProductsDocument,
    "\n  query GetProductsByCategoryWithFragments($slug: String!, $first: Int = 100) {\n    products(where: { category: $slug }, first: $first) {\n      nodes {\n        id\n        slug\n        name\n        __typename\n        shortDescription\n        description\n        ... on ProductWithPricing {\n          price\n        }\n        ... on Product {\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n          productCategories {\n            nodes {\n              id\n              name\n              slug\n            }\n          }\n        }\n        ... on VariableProduct {\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n        ... on SimpleProduct {\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetProductsByCategoryWithFragmentsDocument,
    "\n  query GetPosts {\n    posts(first: 10, where: { orderby: { field: DATE, order: DESC } }) {\n      nodes {\n        id\n        title\n        excerpt\n        slug\n        date\n        featuredImage {\n          node {\n            sourceUrl\n            altText\n            mediaDetails {\n              width\n              height\n            }\n          }\n        }\n        author {\n          node {\n            name\n          }\n        }\n        categories {\n          nodes {\n            name\n          }\n        }\n      }\n    }\n  }\n": types.GetPostsDocument,
    "\n  query GetPostBySlug($slug: ID!) {\n    post(id: $slug, idType: SLUG) {\n      title\n      excerpt\n      content\n      date\n      featuredImage {\n        node {\n          sourceUrl\n          altText\n        }\n      }\n      author {\n        node {\n          name\n          avatar {\n            url\n          }\n        }\n      }\n      categories {\n        nodes {\n          name\n          slug\n        }\n      }\n    }\n  }\n": types.GetPostBySlugDocument,
    "\n  query GetAllPostsSlugs {\n    posts(first: 100) {\n      nodes {\n        slug\n      }\n    }\n  }\n": types.GetAllPostsSlugsDocument,
    "\n  query GetSEOPageContent($slug: String!) {\n    pages(where: { name: $slug }) {\n      nodes {\n        databaseId\n        title\n        content\n        slug\n        date\n        modified\n        featuredImage {\n          node {\n            sourceUrl\n            altText\n          }\n        }\n      }\n    }\n  }\n": types.GetSeoPageContentDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetProductCategories {\n    productCategories(first: 10) {\n      nodes {\n        id\n        name\n        slug\n        description\n        image {\n          sourceUrl\n          altText\n        }\n        count\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetProductCategories {\n    productCategories(first: 10) {\n      nodes {\n        id\n        name\n        slug\n        description\n        image {\n          sourceUrl\n          altText\n        }\n        count\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetDynamicProductsByCategory($categoriaSlug: [String], $cantidad: Int) {\n    productosPorCategoria: products(where: { categoryIn: $categoriaSlug }, first: $cantidad) {\n      nodes {\n        id\n        name\n        slug\n        ... on Product {\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n        ... on SimpleProduct {\n          price\n          regularPrice\n          salePrice\n          shortDescription\n          onSale\n          stockStatus\n          stockQuantity\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n        ... on VariableProduct {\n          price\n          regularPrice\n          salePrice\n          shortDescription\n          onSale\n          stockStatus\n          stockQuantity\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetDynamicProductsByCategory($categoriaSlug: [String], $cantidad: Int) {\n    productosPorCategoria: products(where: { categoryIn: $categoriaSlug }, first: $cantidad) {\n      nodes {\n        id\n        name\n        slug\n        ... on Product {\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n        ... on SimpleProduct {\n          price\n          regularPrice\n          salePrice\n          shortDescription\n          onSale\n          stockStatus\n          stockQuantity\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n        ... on VariableProduct {\n          price\n          regularPrice\n          salePrice\n          shortDescription\n          onSale\n          stockStatus\n          stockQuantity\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetFullVariableProduct($slug: ID!) {\n    product(id: $slug, idType: SLUG) {\n      ... on VariableProduct {\n        id\n        name\n        slug\n        price\n        regularPrice\n        salePrice\n        onSale\n        stockStatus\n        stockQuantity\n        shortDescription\n        description\n        featuredImage {\n          node {\n            sourceUrl\n            altText\n          }\n        }\n        galleryImages {\n          nodes {\n            sourceUrl\n            altText\n          }\n        }\n        productCategories {\n          nodes {\n            id\n            name\n            slug\n          }\n        }\n        attributes {\n          nodes {\n            id\n            name\n            options\n          }\n        }\n        variations(first: 50) {\n          nodes {\n            id\n            name\n            sku\n            price\n            stockStatus\n            stockQuantity\n            attributes {\n              nodes {\n                name\n                value\n              }\n            }\n            image {\n              sourceUrl\n              altText\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetFullVariableProduct($slug: ID!) {\n    product(id: $slug, idType: SLUG) {\n      ... on VariableProduct {\n        id\n        name\n        slug\n        price\n        regularPrice\n        salePrice\n        onSale\n        stockStatus\n        stockQuantity\n        shortDescription\n        description\n        featuredImage {\n          node {\n            sourceUrl\n            altText\n          }\n        }\n        galleryImages {\n          nodes {\n            sourceUrl\n            altText\n          }\n        }\n        productCategories {\n          nodes {\n            id\n            name\n            slug\n          }\n        }\n        attributes {\n          nodes {\n            id\n            name\n            options\n          }\n        }\n        variations(first: 50) {\n          nodes {\n            id\n            name\n            sku\n            price\n            stockStatus\n            stockQuantity\n            attributes {\n              nodes {\n                name\n                value\n              }\n            }\n            image {\n              sourceUrl\n              altText\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetProductsByCategory($categorySlug: ID!, $first: Int = 12) {\n    productCategory(id: $categorySlug, idType: SLUG) {\n      id\n      name\n      slug\n      description\n      image {\n        sourceUrl\n        altText\n      }\n      products(first: $first) {\n        nodes {\n          id\n          name\n          slug\n          ... on ProductWithPricing {\n            price\n            regularPrice\n            salePrice\n          }\n          ... on SimpleProduct {\n            stockStatus\n            onSale\n          }\n          ... on VariableProduct {\n            stockStatus\n            onSale\n          }\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n          productCategories {\n            nodes {\n              id\n              name\n              slug\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetProductsByCategory($categorySlug: ID!, $first: Int = 12) {\n    productCategory(id: $categorySlug, idType: SLUG) {\n      id\n      name\n      slug\n      description\n      image {\n        sourceUrl\n        altText\n      }\n      products(first: $first) {\n        nodes {\n          id\n          name\n          slug\n          ... on ProductWithPricing {\n            price\n            regularPrice\n            salePrice\n          }\n          ... on SimpleProduct {\n            stockStatus\n            onSale\n          }\n          ... on VariableProduct {\n            stockStatus\n            onSale\n          }\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n          productCategories {\n            nodes {\n              id\n              name\n              slug\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetVariableProductsByCategory($category: String!, $first: Int = 50) {\n    products(where: { category: $category }, first: $first) {\n      nodes {\n        ... on VariableProduct {\n          id\n          name\n          slug\n          price\n          productCategories {\n            nodes {\n              name\n              slug\n            }\n          }\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetVariableProductsByCategory($category: String!, $first: Int = 50) {\n    products(where: { category: $category }, first: $first) {\n      nodes {\n        ... on VariableProduct {\n          id\n          name\n          slug\n          price\n          productCategories {\n            nodes {\n              name\n              slug\n            }\n          }\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query SearchProducts($search: String!, $first: Int = 20) {\n    products(where: { search: $search }, first: $first) {\n      nodes {\n        id\n        name\n        slug\n        ... on VariableProduct {\n          price\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query SearchProducts($search: String!, $first: Int = 20) {\n    products(where: { search: $search }, first: $first) {\n      nodes {\n        id\n        name\n        slug\n        ... on VariableProduct {\n          price\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetProductsByCategoryWithFragments($slug: String!, $first: Int = 100) {\n    products(where: { category: $slug }, first: $first) {\n      nodes {\n        id\n        slug\n        name\n        __typename\n        shortDescription\n        description\n        ... on ProductWithPricing {\n          price\n        }\n        ... on Product {\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n          productCategories {\n            nodes {\n              id\n              name\n              slug\n            }\n          }\n        }\n        ... on VariableProduct {\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n        ... on SimpleProduct {\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetProductsByCategoryWithFragments($slug: String!, $first: Int = 100) {\n    products(where: { category: $slug }, first: $first) {\n      nodes {\n        id\n        slug\n        name\n        __typename\n        shortDescription\n        description\n        ... on ProductWithPricing {\n          price\n        }\n        ... on Product {\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n          productCategories {\n            nodes {\n              id\n              name\n              slug\n            }\n          }\n        }\n        ... on VariableProduct {\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n        ... on SimpleProduct {\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetPosts {\n    posts(first: 10, where: { orderby: { field: DATE, order: DESC } }) {\n      nodes {\n        id\n        title\n        excerpt\n        slug\n        date\n        featuredImage {\n          node {\n            sourceUrl\n            altText\n            mediaDetails {\n              width\n              height\n            }\n          }\n        }\n        author {\n          node {\n            name\n          }\n        }\n        categories {\n          nodes {\n            name\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetPosts {\n    posts(first: 10, where: { orderby: { field: DATE, order: DESC } }) {\n      nodes {\n        id\n        title\n        excerpt\n        slug\n        date\n        featuredImage {\n          node {\n            sourceUrl\n            altText\n            mediaDetails {\n              width\n              height\n            }\n          }\n        }\n        author {\n          node {\n            name\n          }\n        }\n        categories {\n          nodes {\n            name\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetPostBySlug($slug: ID!) {\n    post(id: $slug, idType: SLUG) {\n      title\n      excerpt\n      content\n      date\n      featuredImage {\n        node {\n          sourceUrl\n          altText\n        }\n      }\n      author {\n        node {\n          name\n          avatar {\n            url\n          }\n        }\n      }\n      categories {\n        nodes {\n          name\n          slug\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetPostBySlug($slug: ID!) {\n    post(id: $slug, idType: SLUG) {\n      title\n      excerpt\n      content\n      date\n      featuredImage {\n        node {\n          sourceUrl\n          altText\n        }\n      }\n      author {\n        node {\n          name\n          avatar {\n            url\n          }\n        }\n      }\n      categories {\n        nodes {\n          name\n          slug\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetAllPostsSlugs {\n    posts(first: 100) {\n      nodes {\n        slug\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetAllPostsSlugs {\n    posts(first: 100) {\n      nodes {\n        slug\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetSEOPageContent($slug: String!) {\n    pages(where: { name: $slug }) {\n      nodes {\n        databaseId\n        title\n        content\n        slug\n        date\n        modified\n        featuredImage {\n          node {\n            sourceUrl\n            altText\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetSEOPageContent($slug: String!) {\n    pages(where: { name: $slug }) {\n      nodes {\n        databaseId\n        title\n        content\n        slug\n        date\n        modified\n        featuredImage {\n          node {\n            sourceUrl\n            altText\n          }\n        }\n      }\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;